spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:DATABASE-PORT/SCHEMA-NAME
    username: USERNAME
    password: PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: "optional:configserver:http://localhost:8088"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none